.TH NOWM "1" "2022" "K4zoku" "NoWM manual"
.SH NAME
NoWM \- Managing window without a window manager
.SH SYNOPSIS
.B nowm
.SH DESCRIPTION
A dead simple tool to managing windows from the tty, written in shell script.
.SH OPTIONS
\fBresize w h\fR
Shrink or grow the current window by the given w/h arguments
.TP
\fBresize_relative w h\fR
Shrink or grow the current window relatively by the given w/h arguments
.TP
\fBmove x y\fR
Shift the current window by the given x/y coordinates
.TP
\fBmove_relative x y\fR
Shift the current window relatively by the given x/y coordinates
.TP
\fBcenter\fR
Centers the current window.
.TP
\fBsnap (top|bottom|left|right)\fR
Move and resize the current window to fill the DIRECTION half of the screen
.TP
\fBpointer_focus\fR
Focus the window underneath the pointer
.TP
\fBselect_focus\fR
Focus selected window
.TP
\fBclose\fR
Destroy the window but will not try to kill the client controlling it
\fBquit\fR
Close window gracefully, this action sends a request, allowing the application to apply close confirmation mechanics
\fBkill\fR
Destroy the window and kill the client controlling it
\fBlogout\fR
Log user out
.SH REPORTING BUGS
Report bugs to https://github.com/K4zoku/nowm/issues
